apiVersion: apps/v1
kind: Deployment
metadata:
  name: find-max-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: find-max
  template:
    metadata:
      labels:
        app: find-max
    spec:
      containers:
        - name: find-max
          image: yuliatrofimenko/find_max:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"

