name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Установка зависимостей
        run: sudo apt update && sudo apt install -y build-essential checkinstall

      - name: Сборка ПО
        run: make

      - name: Запуск тестов
        run: ./test.sh

  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Установка зависимостей
        run: sudo apt update && sudo apt install -y build-essential checkinstall

      - name: Сборка ПО
        run: make

      - name: Сборка .deb пакета
        run: sudo checkinstall --pkgname=find_max --pkgversion=1.0 --pkggroup=utils -y --install=no

      - name: Переименование и сохранение пакета
        run: mv find_max_1.0-1_amd64.deb find_max.deb

      - name: Сохранение артефакта (.deb пакета)
        uses: actions/upload-artifact@v3
        with:
          name: find_max_package
          path: find_max.deb

